### PR TITLE
Fix themes in check box, slider and switch

### PR DESCRIPTION
**Pull request by aideric**
Theme is not working in Checkbox, slider and switch.
This pull request fix this issue.
Add test case in main.dart for testing

### CODE REVIEW

**Comment by aideric** [comment]
fix issue https://github.com/GiancarloCode/form_bloc/issues/269

**Comment by BreX900** [comment]
The most correct use should be:
```dart
return CheckboxTheme(
       data: fieldTheme.checkboxTheme!,
```
and not:
```dart
     return Theme(
       data: Theme.of(context).copyWith(
         checkboxTheme: fieldTheme.checkboxTheme,
       ),
```
Since the implementation is:
```dart
 static CheckboxThemeData of(BuildContext context) {
    final CheckboxTheme? checkboxTheme = context.dependOnInheritedWidgetOfExactType<CheckboxTheme>();
    return checkboxTheme?.data ?? Theme.of(context).checkboxTheme;
  }
```

The problem is (line116 checkbox_group_field_bloc_builder.dart):
```dart
final checkboxTheme = fieldTheme.checkboxTheme ?? CheckboxTheme.of(context);
```

And in other places

**Comment by aideric** [comment]
I tried your approach, but it didn't work.

In the checkbox, it uses the checkboxTheme in ThemData but not the CheckboxTheme.

https://github.com/flutter/flutter/blob/2b33dae9ba11c98dd50b1291dc73588d74557f2a/packages/flutter/lib/src/material/checkbox.dart#L445-L447

That why we need to use
```dart
     return Theme(
       data: Theme.of(context).copyWith(
         checkboxTheme: fieldTheme.checkboxTheme,
       ),
```
but not 
```dart
return CheckboxTheme(
       data: fieldTheme.checkboxTheme!,
```

**Comment by aideric** [comment]
We may change
from
```dart
final checkboxTheme = fieldTheme.checkboxTheme ?? theme.checkboxTheme;
```
to
```dart
final checkboxTheme = fieldTheme.checkboxTheme ?? CheckboxTheme.of(context);
```
but I think it depends on how the original widget getting the themes

**Comment by BreX900** [comment]
@aideric You're right. Thanks so much

@WahdanZ It is okay for me

**Pull request merged**
