### PR TITLE
Added internalization for `en`, `it`

### PR DESCRIPTION
**Pull request by BreX900**
I added internalization via flutter_intl for the following languages: English, Italian

### CODE REVIEW

**Comment by BreX900** [comment]
@GiancarloCode Is it possible to implement it? It would be very useful to me. Thanks

**Comment by GiancarloCode** [comment]
@BreX900 
Hi, I am not familiar with  flutter_intl, I will check it in two days, sorry.

Meanwhile you can override `defaultErrorBuilder`.

```dart
void main() {
  ...
  FieldBlocBuilder.defaultErrorBuilder = (BuildContext context, String error) {
    switch (error) {
      case FieldBlocValidatorsErrors.requiredInputFieldBloc:
        return FormBlocLocalizations.of(context).requiredInputFieldBloc;
      case FieldBlocValidatorsErrors.requiredBooleanFieldBloc:
        return FormBlocLocalizations.of(context).requiredBooleanFieldBloc;
      case FieldBlocValidatorsErrors.requiredTextFieldBloc:
        return FormBlocLocalizations.of(context).requiredTextFieldBloc;
      case FieldBlocValidatorsErrors.requiredSelectFieldBloc:
        return FormBlocLocalizations.of(context).requiredSelectFieldBloc;
      case FieldBlocValidatorsErrors.requiredMultiSelectFieldBloc:
        return FormBlocLocalizations.of(context).requiredMultiSelectFieldBloc;
      case FieldBlocValidatorsErrors.email:
        return FormBlocLocalizations.of(context).email;
      case FieldBlocValidatorsErrors.passwordMin6Chars:
        return FormBlocLocalizations.of(context).passwordMin6Chars;
      case FieldBlocValidatorsErrors.confirmPassword:
        return FormBlocLocalizations.of(context).confirmPassword;
      default:
        return error;
    }
  };

  runApp(App());
}
```

**Comment by BreX900** [comment]
This is magic. Thanks a lot hahaha

**Comment by GiancarloCode** [comment]
Since we have the new version 0.11.0  and have some breaking changes, this pull request will not work, we will be able to add internationalization and more validators in the future :)

**Pull request closed without merging**
