### PR TITLE
allow custom components

### PR DESCRIPTION
**Pull request by 538023**

### CODE REVIEW

**Comment by 538023** [comment]
its important to make s custom state

**Comment by aaassseee** [comment]
Please explain what you are doing. There is already ways to built custom layout e.g. raw bloc builder. What are your difficulties?

**Comment by 538023** [comment]
@aaassseee
I looked in "TextFieldBlocBuilder" to see how these are implemented as there were no instructions on how to create custom fields.
If there is another way, is there an example?

**Comment by 538023** [comment]
@aaassseee 
```dart
import 'package:flutter/material.dart';
import 'package:flutter_form_bloc/flutter_form_bloc.dart';
import 'package:wifi_iot/wifi_iot.dart';

import 'wifi.dart';
import 'wifi_list.dart';
import 'password_dialog.dart'

class WifiData {
  Wifi wifi;
  String password;
  WifiData(this.wifi, this.password);
}

class WifiSetupBlocState<ExtraData> extends FieldBlocState<WifiData?, WifiData?, ExtraData?> {
  final dynamic Function(WifiData? value) _toJson;
  WifiSetupBlocState({
    required bool isValueChanged,
    required WifiData? initialValue,
    required WifiData? updatedValue,
    required WifiData? value,
    required Object? error,
    required bool isDirty,
    required Suggestions<WifiData?>? suggestions,
    required bool isValidated,
    required bool isValidating,
    FormBloc? formBloc,
    required String name,
    List additionalProps = const <dynamic>[],
    dynamic Function(WifiData? value)? toJson,
    ExtraData? extraData,
  }) : _toJson = toJson ?? ((value) => value), super(
    isValueChanged: isValueChanged,
    initialValue: initialValue,
    updatedValue: updatedValue,
    value: value,
    error: error,
    isDirty: isDirty,
    suggestions: suggestions,
    isValidated: isValidated,
    isValidating: isValidating,
    formBloc: formBloc,
    name: name,
    toJson: toJson,
    extraData: extraData,
  );

  @override
  WifiSetupBlocState<ExtraData> copyWith({
    bool? isValueChanged,
    Param<WifiData?>? initialValue,
    Param<WifiData?>? updatedValue,
    Param<WifiData?>? value,
    Param<Object?>? error,
    bool? isDirty,
    Param<Suggestions<WifiData?>?>? suggestions,
    bool? isValidated,
    bool? isValidating,
    Param<FormBloc?>? formBloc,
    Param<ExtraData?>? extraData,
  }) {
    return WifiSetupBlocState(
      isValueChanged: isValueChanged ?? this.isValueChanged,
      initialValue: initialValue.or(this.initialValue),
      updatedValue: updatedValue.or(this.updatedValue),
      value: value == null ? this.value : value.value,
      error: error == null ? this.error : error.value,
      suggestions: suggestions == null ? this.suggestions : suggestions.value,
      isDirty: isDirty ?? this.isDirty,
      isValidated: isValidated ?? this.isValidated,
      isValidating: isValidating ?? this.isValidating,
      formBloc: formBloc == null ? this.formBloc : formBloc.value,
      name: name,
      toJson: _toJson,
      extraData: extraData == null ? this.extraData : extraData.value,
    );
  }
}

class WifiSetupBloc<ExtraData> extends SingleFieldBloc<WifiData?, WifiData?, WifiSetupBlocState<ExtraData>, ExtraData?> {
  WifiSetupBloc({
    String? name,
    WifiData? initialValue,
    List<Validator<WifiData?>>? validators,
    List<AsyncValidator<WifiData?>>? asyncValidators,
    Duration asyncValidatorDebounceTime = const Duration(milliseconds: 500),
    Suggestions<WifiData?>? suggestions,
    ExtraData? extraData,
  }) : super(
    validators: validators,
    asyncValidators: asyncValidators,
    asyncValidatorDebounceTime: asyncValidatorDebounceTime,
    initialState: WifiSetupBlocState(
      isValueChanged: false,
      initialValue: initialValue,
      updatedValue: initialValue,
      value: initialValue,
      error: FieldBlocUtils.getInitialStateError(
        validators: validators,
        value: initialValue,
      ),
      isDirty: false,
      suggestions: suggestions,
      isValidated: FieldBlocUtils.getInitialIsValidated(
        FieldBlocUtils.getInitialStateIsValidating(
          asyncValidators: asyncValidators,
          validators: validators,
          value: initialValue,
        ),
      ),
      isValidating: FieldBlocUtils.getInitialStateIsValidating(
        asyncValidators: asyncValidators,
        validators: validators,
        value: initialValue,
      ),
      name: FieldBlocUtils.generateName(name),
      toJson: (value) => value,
      extraData: extraData,
    ),
  );

}

/// A material design checkbox.
class WifiSetupBlocBuilder extends StatelessWidget {
  const WifiSetupBlocBuilder({
    Key? key,
    required this.wifiFieldBloc,
    this.enableOnlyWhenFormBlocCanSubmit = false,
    this.isEnabled = true,
    this.errorBuilder,
    this.padding,
    this.nextFocusNode,
    this.animateWhenCanShow = true,
  }) : super(key: key);

  /// {@macro flutter_form_bloc.FieldBlocBuilder.fieldBloc}
  final WifiSetupBloc<dynamic> wifiFieldBloc;

  /// {@macro flutter_form_bloc.FieldBlocBuilder.errorBuilder}
  final FieldBlocErrorBuilder? errorBuilder;

  /// {@macro flutter_form_bloc.FieldBlocBuilder.enableOnlyWhenFormBlocCanSubmit}
  final bool enableOnlyWhenFormBlocCanSubmit;

  /// {@macro flutter_form_bloc.FieldBlocBuilder.isEnabled}
  final bool isEnabled;

  /// {@macro flutter_form_bloc.FieldBlocBuilder.padding}
  final EdgeInsetsGeometry? padding;

  /// {@macro flutter_form_bloc.FieldBlocBuilder.nextFocusNode}
  final FocusNode? nextFocusNode;

  /// {@macro  flutter_form_bloc.FieldBlocBuilder.animateWhenCanShow}
  final bool animateWhenCanShow;

  @override
  Widget build(BuildContext context) {
    return CanShowFieldBlocBuilder(
      fieldBloc: wifiFieldBloc,
      animate: animateWhenCanShow,
      builder: (_, __) {
        return BlocBuilder<WifiSetupBloc, WifiSetupBlocState>(
          bloc: wifiFieldBloc,
          builder: (context, state) {
            final isEnabled = fieldBlocIsEnabled(
              isEnabled: this.isEnabled,
              enableOnlyWhenFormBlocCanSubmit:
              enableOnlyWhenFormBlocCanSubmit,
              fieldBlocState: state,
            );

            return DefaultFieldBlocBuilderPadding(
              padding: padding,
              child: _buildWidget(context, isEnabled, state),
            );
          },
        );
      },
    );
  }

  Widget _buildWidget(BuildContext context, bool isEnabled, WifiSetupBlocState state) {
    return OutlinedButton(
      onPressed: isEnabled ? () {
        showDialog(
          context: context,
          builder: (wlancontext) {
            return AlertDialog(
              title: const Text("WLAN"),
              content: WillPopScope(
                  child: SingleChildScrollView(
                    child: SizedBox(
                      width: double.maxFinite,
                      child: WifiList(
                        onConnected: (wifi) {
                          showDialog(
                            context: wlancontext,
                            builder: (passwordcontext) {
                              return WillPopScope(
                                  child: PasswordDialog(
                                    title: wifi.wifiName,
                                    accept: "Bestätigen",
                                    abort: "Abbrechen",
                                    onAccept: (pw) {
                                      WiFiForIoTPlugin.getSSID()
                                          .then((value) {
                                        wifi
                                            .connect(pw)
                                            .then((value) {
                                          if (value) {
                                            Navigator.of(wlancontext)
                                                .pop();
                                            Navigator.of(
                                                passwordcontext)
                                                .pop();
                                            var onChange = fieldBlocBuilderOnChange<WifiData?>(
                                              isEnabled: isEnabled,
                                              nextFocusNode: nextFocusNode,
                                              onChanged: wifiFieldBloc.changeValue,
                                            );
                                            if(onChange != null) onChange(WifiData(wifi, pw));
                                          } else {
                                            ScaffoldMessenger.of(
                                                context)
                                                .showSnackBar(
                                                const SnackBar(
                                                    content: Text(
                                                        "WLAN konnte nicht verbunden werden")));
                                          }
                                        });
                                      });
                                    },
                                    onAbort: () {
                                      Navigator.of(passwordcontext)
                                          .pop();
                                    },
                                  ),
                                  onWillPop: () async => false);
                            },
                            barrierDismissible: false,
                          );
                        },
                      ),
                    ),
                  ),
                  onWillPop: () async => false),
              actions: [
                OutlinedButton(
                    onPressed: () {
                      Navigator.of(wlancontext).pop();
                    },
                    child: const Text("Abbrechen")),
              ],
            );
          },
          barrierDismissible: false,
        );
      } : null,
      child: state.value == null
          ? const Text("Einrichten")
          : Text(state.value!.wifi.wifiName),
    );
  }
}

```

**Comment by aaassseee** [comment]
Lets move to #316 to discuss.

> @aaassseee I looked in "TextFieldBlocBuilder" to see how these are implemented as there were no instructions on how to create custom fields. If there is another way, is there an example?



> @aaassseee
> 
> ```dart
> import 'package:flutter/material.dart';
> import 'package:flutter_form_bloc/flutter_form_bloc.dart';
> import 'package:wifi_iot/wifi_iot.dart';
> 
> import 'wifi.dart';
> import 'wifi_list.dart';
> import 'password_dialog.dart'
> 
> class WifiData {
>   Wifi wifi;
>   String password;
>   WifiData(this.wifi, this.password);
> }
> 
> class WifiSetupBlocState<ExtraData> extends FieldBlocState<WifiData?, WifiData?, ExtraData?> {
>   final dynamic Function(WifiData? value) _toJson;
>   WifiSetupBlocState({
>     required bool isValueChanged,
>     required WifiData? initialValue,
>     required WifiData? updatedValue,
>     required WifiData? value,
>     required Object? error,
>     required bool isDirty,
>     required Suggestions<WifiData?>? suggestions,
>     required bool isValidated,
>     required bool isValidating,
>     FormBloc? formBloc,
>     required String name,
>     List additionalProps = const <dynamic>[],
>     dynamic Function(WifiData? value)? toJson,
>     ExtraData? extraData,
>   }) : _toJson = toJson ?? ((value) => value), super(
>     isValueChanged: isValueChanged,
>     initialValue: initialValue,
>     updatedValue: updatedValue,
>     value: value,
>     error: error,
>     isDirty: isDirty,
>     suggestions: suggestions,
>     isValidated: isValidated,
>     isValidating: isValidating,
>     formBloc: formBloc,
>     name: name,
>     toJson: toJson,
>     extraData: extraData,
>   );
> 
>   @override
>   WifiSetupBlocState<ExtraData> copyWith({
>     bool? isValueChanged,
>     Param<WifiData?>? initialValue,
>     Param<WifiData?>? updatedValue,
>     Param<WifiData?>? value,
>     Param<Object?>? error,
>     bool? isDirty,
>     Param<Suggestions<WifiData?>?>? suggestions,
>     bool? isValidated,
>     bool? isValidating,
>     Param<FormBloc?>? formBloc,
>     Param<ExtraData?>? extraData,
>   }) {
>     return WifiSetupBlocState(
>       isValueChanged: isValueChanged ?? this.isValueChanged,
>       initialValue: initialValue.or(this.initialValue),
>       updatedValue: updatedValue.or(this.updatedValue),
>       value: value == null ? this.value : value.value,
>       error: error == null ? this.error : error.value,
>       suggestions: suggestions == null ? this.suggestions : suggestions.value,
>       isDirty: isDirty ?? this.isDirty,
>       isValidated: isValidated ?? this.isValidated,
>       isValidating: isValidating ?? this.isValidating,
>       formBloc: formBloc == null ? this.formBloc : formBloc.value,
>       name: name,
>       toJson: _toJson,
>       extraData: extraData == null ? this.extraData : extraData.value,
>     );
>   }
> }
> 
> class WifiSetupBloc<ExtraData> extends SingleFieldBloc<WifiData?, WifiData?, WifiSetupBlocState<ExtraData>, ExtraData?> {
>   WifiSetupBloc({
>     String? name,
>     WifiData? initialValue,
>     List<Validator<WifiData?>>? validators,
>     List<AsyncValidator<WifiData?>>? asyncValidators,
>     Duration asyncValidatorDebounceTime = const Duration(milliseconds: 500),
>     Suggestions<WifiData?>? suggestions,
>     ExtraData? extraData,
>   }) : super(
>     validators: validators,
>     asyncValidators: asyncValidators,
>     asyncValidatorDebounceTime: asyncValidatorDebounceTime,
>     initialState: WifiSetupBlocState(
>       isValueChanged: false,
>       initialValue: initialValue,
>       updatedValue: initialValue,
>       value: initialValue,
>       error: FieldBlocUtils.getInitialStateError(
>         validators: validators,
>         value: initialValue,
>       ),
>       isDirty: false,
>       suggestions: suggestions,
>       isValidated: FieldBlocUtils.getInitialIsValidated(
>         FieldBlocUtils.getInitialStateIsValidating(
>           asyncValidators: asyncValidators,
>           validators: validators,
>           value: initialValue,
>         ),
>       ),
>       isValidating: FieldBlocUtils.getInitialStateIsValidating(
>         asyncValidators: asyncValidators,
>         validators: validators,
>         value: initialValue,
>       ),
>       name: FieldBlocUtils.generateName(name),
>       toJson: (value) => value,
>       extraData: extraData,
>     ),
>   );
> 
> }
> 
> /// A material design checkbox.
> class WifiSetupBlocBuilder extends StatelessWidget {
>   const WifiSetupBlocBuilder({
>     Key? key,
>     required this.wifiFieldBloc,
>     this.enableOnlyWhenFormBlocCanSubmit = false,
>     this.isEnabled = true,
>     this.errorBuilder,
>     this.padding,
>     this.nextFocusNode,
>     this.animateWhenCanShow = true,
>   }) : super(key: key);
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.fieldBloc}
>   final WifiSetupBloc<dynamic> wifiFieldBloc;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.errorBuilder}
>   final FieldBlocErrorBuilder? errorBuilder;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.enableOnlyWhenFormBlocCanSubmit}
>   final bool enableOnlyWhenFormBlocCanSubmit;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.isEnabled}
>   final bool isEnabled;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.padding}
>   final EdgeInsetsGeometry? padding;
> 
>   /// {@macro flutter_form_bloc.FieldBlocBuilder.nextFocusNode}
>   final FocusNode? nextFocusNode;
> 
>   /// {@macro  flutter_form_bloc.FieldBlocBuilder.animateWhenCanShow}
>   final bool animateWhenCanShow;
> 
>   @override
>   Widget build(BuildContext context) {
>     return CanShowFieldBlocBuilder(
>       fieldBloc: wifiFieldBloc,
>       animate: animateWhenCanShow,
>       builder: (_, __) {
>         return BlocBuilder<WifiSetupBloc, WifiSetupBlocState>(
>           bloc: wifiFieldBloc,
>           builder: (context, state) {
>             final isEnabled = fieldBlocIsEnabled(
>               isEnabled: this.isEnabled,
>               enableOnlyWhenFormBlocCanSubmit:
>               enableOnlyWhenFormBlocCanSubmit,
>               fieldBlocState: state,
>             );
> 
>             return DefaultFieldBlocBuilderPadding(
>               padding: padding,
>               child: _buildWidget(context, isEnabled, state),
>             );
>           },
>         );
>       },
>     );
>   }
> 
>   Widget _buildWidget(BuildContext context, bool isEnabled, WifiSetupBlocState state) {
>     return OutlinedButton(
>       onPressed: isEnabled ? () {
>         showDialog(
>           context: context,
>           builder: (wlancontext) {
>             return AlertDialog(
>               title: const Text("WLAN"),
>               content: WillPopScope(
>                   child: SingleChildScrollView(
>                     child: SizedBox(
>                       width: double.maxFinite,
>                       child: WifiList(
>                         onConnected: (wifi) {
>                           showDialog(
>                             context: wlancontext,
>                             builder: (passwordcontext) {
>                               return WillPopScope(
>                                   child: PasswordDialog(
>                                     title: wifi.wifiName,
>                                     accept: "Bestätigen",
>                                     abort: "Abbrechen",
>                                     onAccept: (pw) {
>                                       WiFiForIoTPlugin.getSSID()
>                                           .then((value) {
>                                         wifi
>                                             .connect(pw)
>                                             .then((value) {
>                                           if (value) {
>                                             Navigator.of(wlancontext)
>                                                 .pop();
>                                             Navigator.of(
>                                                 passwordcontext)
>                                                 .pop();
>                                             var onChange = fieldBlocBuilderOnChange<WifiData?>(
>                                               isEnabled: isEnabled,
>                                               nextFocusNode: nextFocusNode,
>                                               onChanged: wifiFieldBloc.changeValue,
>                                             );
>                                             if(onChange != null) onChange(WifiData(wifi, pw));
>                                           } else {
>                                             ScaffoldMessenger.of(
>                                                 context)
>                                                 .showSnackBar(
>                                                 const SnackBar(
>                                                     content: Text(
>                                                         "WLAN konnte nicht verbunden werden")));
>                                           }
>                                         });
>                                       });
>                                     },
>                                     onAbort: () {
>                                       Navigator.of(passwordcontext)
>                                           .pop();
>                                     },
>                                   ),
>                                   onWillPop: () async => false);
>                             },
>                             barrierDismissible: false,
>                           );
>                         },
>                       ),
>                     ),
>                   ),
>                   onWillPop: () async => false),
>               actions: [
>                 OutlinedButton(
>                     onPressed: () {
>                       Navigator.of(wlancontext).pop();
>                     },
>                     child: const Text("Abbrechen")),
>               ],
>             );
>           },
>           barrierDismissible: false,
>         );
>       } : null,
>       child: state.value == null
>           ? const Text("Einrichten")
>           : Text(state.value!.wifi.wifiName),
>     );
>   }
> }
> ```

**Pull request closed without merging**
