### PR TITLE
Converted `SingleFieldBloc`, `ListFieldBloc`, `GroupFieldBloc` to `Cubit`

### LINKED ISSUE #228: wait for update values
@GiancarloCode is it safe to use the following code

```dart
print(myField.value); // 0
myField.updateValue(1);
print(myField.value); // 0 because the value updates in async way
await this.stream.first;
print(myField.value); // 1
```

I want to have the updated values for subsequent calculation

### PR DESCRIPTION
**Pull request by SimoneBressan**
Added basic methods to the `FieldBloc` interface (maybe we should also have a shared state among all FieldBlocs?)
Fixed double calls in `FormBloc` to add or remove fieldBlocs

Fix #228

### CODE REVIEW

**Comment by WahdanZ** [comment]
what's the state could be shared between all FieldBlocs?

**Comment by SimoneBressan** [comment]
For example
```dart
class SharedFieldState {
  final String name;
  final Form? form;

  SharedFieldState({required this.name, required this.form});

  SharedFieldState copyWith({
    Param<Form?> form;
  });
}
```
So that you can handle the logic of form handling in `FieldBloc` so this class should also extend `Cubit`

I don't know if it can simplify or complicate the code

**Comment by SimoneBressan** [comment]
@WahdanZ Is there anything I need to update?
So then I port to bloc: `^ 8.0.0`
Thanks

**Comment by WahdanZ** [comment]
I think we can start migrate to bloc 8.0 before merge , then I'll going to publish the new version

**Review by WahdanZ — APPROVED** [review]

**Pull request merged**
