### PR TITLE
null safety  migrate

### PR DESCRIPTION
**Pull request by WahdanZ**

### CODE REVIEW

**Comment by sm2017** [comment]
@WahdanZ I switched to your fork
```yaml
  flutter_form_bloc:
    git:
      url: https://github.com/WahdanZ/form_bloc
      ref: ns-mirgrate
      path: packages/flutter_form_bloc
```

Validators such as `FieldBlocValidators.required` is runned at initial time, When the form is loaded all fields has error!

**Comment by WahdanZ** [comment]
fixed can you check again

**Comment by sm2017** [comment]
@WahdanZ It fixed, Thanks

**Comment by WahdanZ** [comment]
@sm2017 
you can test the Prerelease versions that support null safety

dependencies:
  form_bloc: ^0.20.0-nullsafety.0
  flutter_form_bloc: ^0.20.0-nullsafety.0

**Pull request closed without merging**
